const translations = {
  en: {
    title: 'Leon Weigang | Portfolio',
    skipContent: 'Skip to content',
    homeAria: 'Leon Weigang home',
    languageSwitcher: 'Language switcher',
    mobileNavigation: 'Mobile navigation',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    navAbout: 'About me',
    navSkills: 'Skills',
    navPortfolio: 'Portfolio',
    navContact: 'Contact',
    heroIAm: 'I am',
    heroRole: 'FRONTEND DEVELOPER',
    heroCta: "Let's talk!",
    scrollAbout: 'Scroll to About me',
    scrollDown: 'Scroll down',
    aboutTitle: 'About me',
    aboutLead: "Hey there, I'm Leon!<br>I build modern, user-friendly web experiences and enjoy solving problems with clean, structured code.",
    aboutLocated: 'I am based in Germany and am open to different ways of working, including remote collaboration and relocation.',
    aboutMindset: 'I am open-minded, curious and motivated to keep learning new technologies and continually improve my skills.',
    aboutProblem: 'I approach challenges analytically and creatively, learn from every problem and look for efficient solutions through persistence and collaboration.',
    skillsTitle: 'Skills',
    skillsText: 'I enjoy working on different projects with modern front-end technologies such as HTML, CSS, JavaScript, TypeScript and Angular. I am also open to learning and adapting to new technologies because continuous education is essential in fast-moving web development.',
    skillsQuestion: 'Looking for <span>another skill?</span>',
    skillsQuestionText: 'I am always enthusiastic about learning new technologies and frameworks.',
    getInTouch: 'Get in touch',
    portfolioTitle: 'Portfolio',
    portfolioText: 'Explore a selection of my work here – Interact with projects<br class="desktop-only"> to see my skills in action.',
    openProject: 'Open project ↗',
    openElPolloLoco: 'Open El Pollo Loco project',
    openJoin: 'Open JOIN project',
    openDaBubble: 'Open daBubble project',
    openPokedex: 'Open Pokédex project',
    testimonialSection: 'Testimonials',
    testimonialControls: 'Testimonial controls',
    previousTestimonial: 'Previous testimonial',
    nextTestimonial: 'Next testimonial',
    testimonialNumber: 'Testimonial {number}',
    contactTitle: 'Contact',
    contactHeading: 'Got a problem to solve?',
    contactText: 'Tell me what you are looking for and what role you are interested in. I would love to add value to your projects with reliable and thoughtful front-end development.',
    contactCta: 'Need a Frontend developer? <strong>Contact me!</strong>',
    nameLabel: 'Your name',
    namePlaceholder: 'Your name',
    emailLabel: 'Your email',
    emailPlaceholder: 'Your email',
    messageLabel: 'Your message',
    messagePlaceholder: 'Your message',
    privacyConsent: 'I\'ve read the <a href="privacy-policy.html">privacy policy</a> and agree to the processing of my data as outlined.',
    sendMessage: 'Send message :)',
    backToTop: 'Back to top',
    legalNotice: 'Legal Notice',
    validationName: 'Please enter at least 2 characters.',
    validationEmail: 'Please enter a valid email address.',
    validationMessage: 'Please enter at least 10 characters.',
    validationPrivacy: 'Please confirm the Privacy Policy.',
    endpointMissing: 'Please configure your form endpoint first.',
    sending: 'Sending ...',
    success: 'Thank you! Your message has been sent successfully.',
    failure: 'The form could not be submitted. Please try again later.',
    learningPopup: 'I have a special interest in learning',
    learningPython: 'Python',
    learningKi: 'Ki',
    github: 'Github',
    liveTest: 'Live test',
    projectElPolloLocoTitle: 'El Pollo Loco',
    projectElPolloLocoDescription: 'Jump, run and throw game based on object-oriented approach. Help Pepe to find coins and tabasco salsa to fight against the crazy hen.',
    projectElPolloLocoTech: 'JavaScript | HTML | CSS',
    projectJoinTitle: 'Join',
    projectJoinDescription: 'Task manager inspired by the Kanban System. Create and organize tasks using drag and drop functions, assign users and categories.',
    projectJoinTech: 'Angular | TypeScript | HTML | CSS | Firebase',
    projectDaBubbleTitle: 'daBubble',
    projectPokedexTitle: 'Pokédex',
    projectPlaceholderDescription: 'Add the project description here.',
    projectPlaceholderTech: 'Add technologies here.',
    altElPolloLoco: 'El Pollo Loco project preview',
    altJoin: 'JOIN project preview',
    altDaBubble: 'daBubble project preview',
    altPokedex: 'Pokédex project preview',
    legalPageTitle: 'Legal Notice | Leon Weigang',
    privacyPageTitle: 'Privacy Policy | Leon Weigang',
    navBack: 'Back to portfolio',
    legalTitle: 'Legal Notice',
    legalImprintHeading: 'Imprint',
    legalContactHeading: 'Contact',
    legalDisclaimerHeading: 'Disclaimer',
    legalDisclaimerText: 'This legal notice is a project placeholder. Replace the personal and business details with your real information and complete the legally required content before publication.',
    privacyTitle: 'Privacy Policy',
    privacyIntroHeading: 'General information',
    privacyIntroText: 'This page is a project template. Before going live, replace the text below with a privacy policy that accurately describes your hosting, analytics, fonts, contact form provider, embedded content and any other services used on this website.',
    privacyContactHeading: 'Contact form',
    privacyContactText: 'The contact form should only transmit the personal data that is necessary to process your enquiry. Replace the placeholder Formspree endpoint in the HTML with your configured provider and make sure its privacy documentation is reflected here.',
    privacyHostingHeading: 'Hosting and server logs',
    privacyHostingText: 'Your final privacy policy should state which hosting provider is used, which technical data may be processed in server logs and how long that data is retained.',
    privacyRightsHeading: 'Your rights',
    privacyRightsText: 'Your final privacy policy should explain the applicable data protection rights and provide a current contact route for privacy enquiries.'
  },
  de: {
    title: 'Leon Weigang | Portfolio',
    skipContent: 'Zum Inhalt springen',
    homeAria: 'Leon Weigang Startseite',
    languageSwitcher: 'Sprachauswahl',
    mobileNavigation: 'Mobile Navigation',
    menuOpen: 'Menü öffnen',
    menuClose: 'Menü schließen',
    navAbout: 'Über mich',
    navSkills: 'Skills',
    navPortfolio: 'Portfolio',
    navContact: 'Kontakt',
    heroIAm: 'Ich bin',
    heroRole: 'FRONTEND ENTWICKLER',
    heroCta: 'Lass uns reden!',
    scrollAbout: 'Zu Über mich scrollen',
    scrollDown: 'Nach unten',
    aboutTitle: 'Über mich',
    aboutLead: 'Hey, ich bin Leon!<br>Ich entwickle moderne, benutzerfreundliche Webanwendungen und löse gerne Probleme mit sauberem, strukturiertem Code.',
    aboutLocated: 'Ich lebe in Deutschland und bin offen für verschiedene Arbeitsmodelle, Remote-Zusammenarbeit und einen Umzug.',
    aboutMindset: 'Ich bin aufgeschlossen, neugierig und motiviert, neue Technologien zu lernen und meine Fähigkeiten kontinuierlich weiterzuentwickeln.',
    aboutProblem: 'Ich gehe Herausforderungen analytisch und kreativ an, lerne aus jedem Problem und suche durch Ausdauer und Zusammenarbeit nach effizienten Lösungen.',
    skillsTitle: 'Skills',
    skillsText: 'Ich arbeite gerne an unterschiedlichen Projekten mit modernen Frontend-Technologien wie HTML, CSS, JavaScript, TypeScript und Angular. Gleichzeitig bin ich offen dafür, neue Technologien zu lernen und mich weiterzuentwickeln, weil kontinuierliche Weiterbildung in der schnelllebigen Webentwicklung wichtig ist.',
    skillsQuestion: 'Du suchst nach <span>einem weiteren Skill?</span>',
    skillsQuestionText: 'Ich lerne mit Begeisterung neue Technologien und Frameworks.',
    getInTouch: 'Kontakt aufnehmen',
    portfolioTitle: 'Portfolio',
    portfolioText: 'Hier findest du eine Auswahl meiner Arbeiten – Interagiere mit den Projekten<br class="desktop-only"> und entdecke meine Skills in Aktion.',
    openProject: 'Projekt öffnen ↗',
    openElPolloLoco: 'El Pollo Loco Projekt öffnen',
    openJoin: 'JOIN Projekt öffnen',
    openDaBubble: 'daBubble Projekt öffnen',
    openPokedex: 'Pokédex Projekt öffnen',
    testimonialSection: 'Referenzen',
    testimonialControls: 'Referenz-Navigation',
    previousTestimonial: 'Vorherige Referenz',
    nextTestimonial: 'Nächste Referenz',
    testimonialNumber: 'Referenz {number}',
    contactTitle: 'Kontakt',
    contactHeading: 'Du hast ein Problem zu lösen?',
    contactText: 'Erzähl mir, was du suchst und für welche Rolle du dich interessierst. Ich unterstütze deine Projekte gerne mit zuverlässiger und durchdachter Frontend-Entwicklung.',
    contactCta: 'Du suchst einen Frontend-Entwickler? <strong>Kontaktiere mich!</strong>',
    nameLabel: 'Dein Name',
    namePlaceholder: 'Dein Name',
    emailLabel: 'Deine E-Mail',
    emailPlaceholder: 'Deine E-Mail',
    messageLabel: 'Deine Nachricht',
    messagePlaceholder: 'Deine Nachricht',
    privacyConsent: 'Ich habe die <a href="privacy-policy.html">Datenschutzerklärung</a> gelesen und stimme der Verarbeitung meiner Daten wie dort beschrieben zu.',
    sendMessage: 'Nachricht senden :)',
    backToTop: 'Nach oben',
    legalNotice: 'Impressum',
    validationName: 'Bitte gib mindestens 2 Zeichen ein.',
    validationEmail: 'Bitte gib eine gültige E-Mail-Adresse ein.',
    validationMessage: 'Bitte gib mindestens 10 Zeichen ein.',
    validationPrivacy: 'Bitte bestätige die Datenschutzerklärung.',
    endpointMissing: 'Bitte hinterlege zuerst deinen Formular-Endpunkt.',
    sending: 'Wird gesendet ...',
    success: 'Danke! Deine Nachricht wurde erfolgreich gesendet.',
    failure: 'Die Nachricht konnte nicht gesendet werden. Bitte versuche es später erneut.',
    learningPopup: 'Ich habe ein besonderes Interesse am Lernen',
    learningPython: 'Python',
    learningKi: 'Ki',
    github: 'Github',
    liveTest: 'Live test',
    projectElPolloLocoTitle: 'El Pollo Loco',
    projectElPolloLocoDescription: 'Jump-and-run-Spiel auf objektorientierter Basis. Hilf Pepe dabei, Münzen und Tabasco-Salsa zu finden und gegen die verrückte Henne zu kämpfen.',
    projectElPolloLocoTech: 'JavaScript | HTML | CSS',
    projectJoinTitle: 'Join',
    projectJoinDescription: 'Auf dem Kanban-System basierender Task-Manager. Erstelle und organisiere Aufgaben per Drag-and-Drop und weise Benutzer und Kategorien zu.',
    projectJoinTech: 'Angular | TypeScript | HTML | CSS | Firebase',
    projectDaBubbleTitle: 'daBubble',
    projectPokedexTitle: 'Pokédex',
    projectPlaceholderDescription: 'Projektbeschreibung hier ergänzen.',
    projectPlaceholderTech: 'Technologien hier ergänzen.',
    altElPolloLoco: 'Projektvorschau von El Pollo Loco',
    altJoin: 'Projektvorschau von JOIN',
    altDaBubble: 'Projektvorschau von daBubble',
    altPokedex: 'Projektvorschau des Pokédex',
    legalPageTitle: 'Impressum | Leon Weigang',
    privacyPageTitle: 'Datenschutz | Leon Weigang',
    navBack: 'Zurück zum Portfolio',
    legalTitle: 'Impressum',
    legalImprintHeading: 'Angaben gemäß Impressum',
    legalContactHeading: 'Kontakt',
    legalDisclaimerHeading: 'Haftungshinweis',
    legalDisclaimerText: 'Dies ist eine Projektvorlage. Ersetze die persönlichen und geschäftlichen Angaben durch deine echten Daten und vervollständige vor der Veröffentlichung alle gesetzlich erforderlichen Inhalte.',
    privacyTitle: 'Datenschutzerklärung',
    privacyIntroHeading: 'Allgemeine Hinweise',
    privacyIntroText: 'Diese Seite ist eine Projektvorlage. Vor der Veröffentlichung musst du eine Datenschutzerklärung einsetzen, die Hosting, Analyse-Tools, Schriften, Formularanbieter, eingebundene Inhalte und alle weiteren auf dieser Website verwendeten Dienste korrekt beschreibt.',
    privacyContactHeading: 'Kontaktformular',
    privacyContactText: 'Das Kontaktformular sollte nur die personenbezogenen Daten übertragen, die zur Bearbeitung deiner Anfrage erforderlich sind. Ersetze den Platzhalter-Endpunkt von Formspree durch deinen konfigurierten Anbieter und berücksichtige dessen Datenschutzinformationen.',
    privacyHostingHeading: 'Hosting und Server-Logs',
    privacyHostingText: 'In deiner endgültigen Datenschutzerklärung sollte stehen, welcher Hostinganbieter eingesetzt wird, welche technischen Daten in Server-Logs verarbeitet werden können und wie lange diese Daten gespeichert werden.',
    privacyRightsHeading: 'Deine Rechte',
    privacyRightsText: 'Die endgültige Datenschutzerklärung sollte die jeweils geltenden Datenschutzrechte erläutern und einen aktuellen Kontaktweg für Datenschutzanfragen nennen.'
  }
};

const testimonials = [
  {
    en: {
      text: 'Working with Leon was highly constructive. He combines clear communication with a strong attention to detail. He demonstrated exceptional commitment to the project, regularly going the extra mile to resolve critical hurdles. Leon was also responsible for the project\'s most substantial core component, which he mastered with outstanding technical skill and efficiency.',
      author: 'Curtis N.W. - Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/curtis.png'
    },
    de: {
      text: 'Die Zusammenarbeit mit Leon war äußerst konstruktiv. Er verbindet klare Kommunikation mit großer Liebe zum Detail. Er zeigte außergewöhnliches Engagement für das Projekt und scheute keine Mühen, um kritische Hürden zu überwinden. Leon war zudem für die wichtigste Kernkomponente des Projekts verantwortlich, die er mit herausragendem technischem Können und großer Effizienz meisterte.',
      author: 'Curtis N.W. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/curtis.png'
    }
  },
  {
    en: {
      text: 'Leon was a fantastic team member, on whom you can always rely completely. He stands out through a focused approach to work and was significantly responsible for the technical foundation of our project. He implemented this key element with great skill and attention to detail. In our group meetings, Leon shone through clear and understandable communication and was always ready to help the team. His expertise and commitment were a real asset to our project.',
      author: 'Kamil M. – Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/Kamil.png'
    },
    de: {
      text: 'Leon war ein fantastischer Teampartner, auf den man sich jederzeit voll verlassen konnte. Er zeichnete sich durch eine fokussierte Arbeitsweise aus und war maßgeblich für das technische Fundament unseres Projekts verantwortlich. Dieses Schlüsselelement setzte er mit großem Geschick und Liebe zum Detail um. In unseren Gruppengesprächen glänzte Leon durch eine klare, verständliche Kommunikation und stand dem Team immer hilfsbereit zur Seite. Seine Expertise und sein Engagement waren ein echter Gewinn für unser Projekt.',
      author: 'Kamil M. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/Kamil.png'
    }
  },
  {
    en: {
      text: 'Thanks to his exceptional dedication and perseverance, Leon has made a major contribution to the project. Even when faced with difficult problems, he kept at it – often late into the night – and impressed with his meticulous work and high standards.',
      author: 'Annika E. – Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/annika.png'
    },
    de: {
      text: 'Leon hat durch seinen außergewöhnlichen Einsatz und seine Ausdauer einen großen Beitrag zum Projekt geleistet. Auch bei schwierigen Problemen blieb er dran – oft bis spät in die Nacht – und überzeugte mit sorgfältiger Arbeit und hoher Qualität.',
      author: 'Annika E. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/annika.png'
    }
  }
];

export { translations, testimonials };
