const translations = {
  en: {
    title: 'Leon Weigang | Portfolio',
    skipContent: 'Skip to content',
    homeAria: 'Leon Weigang home',
    languageSwitcher: 'Language switcher',
    mobileNavigation: 'Mobile navigation',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    navAbout: 'About me',
    navSkills: 'Skills',
    navPortfolio: 'Portfolio',
    navContact: 'Contact',
    heroIAm: 'I am',
    heroRole: 'FRONTEND DEVELOPER',
    heroCta: "Let's talk!",
    scrollAbout: 'Scroll to About me',
    scrollDown: 'Scroll down',
    aboutTitle: 'About me',
    aboutLead: "Hey there, I'm Leon!<br>I build modern, user-friendly web experiences and enjoy solving problems with clean, structured code.",
    aboutLocated: 'Based in Stuttgart, Germany — open to remote work, hybrid setups, or relocating for the right opportunity.',
    aboutMindset: 'I am open-minded, curious and motivated to keep learning new technologies and continually improve my skills.',
    aboutProblem: 'I approach challenges analytically and creatively, learn from every problem and look for efficient solutions through persistence and collaboration.',
    skillsTitle: 'Skills',
    skillsText: 'I enjoy working on different projects with modern front-end technologies such as HTML, CSS, JavaScript, TypeScript and Angular. I am also open to learning and adapting to new technologies because continuous education is essential in fast-moving web development.',
    skillsQuestion: 'Looking for <span>another skill?</span>',
    skillsQuestionText: 'I am always enthusiastic about learning new technologies and frameworks.',
    getInTouch: 'Get in touch',
    portfolioTitle: 'Portfolio',
    portfolioText: 'Explore a selection of my work here – Interact with projects<br class="desktop-only"> to see my skills in action.',
    openProject: 'Open project ↗',
    openElPolloLoco: 'Open El Pollo Loco project',
    openJoin: 'Open JOIN project',
    openDaBubble: 'Open daBubble project',
    openPokedex: 'Open Pokédex project',
    testimonialSection: 'Testimonials',
    testimonialControls: 'Testimonial controls',
    previousTestimonial: 'Previous testimonial',
    nextTestimonial: 'Next testimonial',
    testimonialNumber: 'Testimonial {number}',
    contactTitle: 'Contact',
    contactHeading: 'Got a problem to solve?',
    contactText: 'Tell me what you are looking for and what role you are interested in. I would love to add value to your projects with reliable and thoughtful front-end development.',
    contactCta: 'Need a Frontend developer? <strong>Contact me!</strong>',
    nameLabel: 'Your name',
    namePlaceholder: 'Your name',
    emailLabel: 'Your email',
    emailPlaceholder: 'Your email',
    messageLabel: 'Your message',
    messagePlaceholder: 'Your message',
    privacyConsent: 'I\'ve read the <a href="privacy-policy.html">privacy policy</a> and agree to the processing of my data as outlined.',
    sendMessage: 'Send message :)',
    backToTop: 'Back to top',
    legalNotice: 'Legal Notice',
    validationName: 'Please enter at least 2 characters.',
    validationEmail: 'Please enter a valid email address.',
    validationMessage: 'Please enter at least 10 characters.',
    validationPrivacy: 'Please confirm the Privacy Policy.',
    endpointMissing: 'Please configure your form endpoint first.',
    sending: 'Sending ...',
    success: 'Thank you! Your message has been sent successfully.',
    failure: 'The form could not be submitted. Please try again later.',
    learningPopup: 'I have a special interest in learning',
    learningPython: 'Python',
    learningKi: 'Ki',
    github: 'Github',
    liveTest: 'Live test',
    projectElPolloLocoTitle: 'El Pollo Loco',
    projectElPolloLocoDescription: 'Jump, run and throw game based on object-oriented approach. Help Pepe to find coins and tabasco salsa to fight against the crazy hen.',
    projectElPolloLocoTech: 'JavaScript | HTML | CSS',
    projectJoinTitle: 'Join',
    projectJoinDescription: 'Task manager inspired by the Kanban System. Create and organize tasks using drag and drop functions, assign users and categories.',
    projectJoinTech: 'Angular | TypeScript | HTML | CSS | Firebase',
    projectDaBubbleTitle: 'daBubble',
    projectPokedexTitle: 'Pokédex',
    projectPlaceholderDescription: 'Add the project description here.',
    projectPlaceholderTech: 'Add technologies here.',
    altElPolloLoco: 'El Pollo Loco project preview',
    altJoin: 'JOIN project preview',
    altDaBubble: 'daBubble project preview',
    altPokedex: 'Pokédex project preview',
    legalPageTitle: 'Legal Notice | Leon Weigang',
    privacyPageTitle: 'Privacy Policy | Leon Weigang',
    navBack: 'Back to portfolio',
    legalTitle: 'Legal Notice',
    legalImprintHeading: 'Imprint',
    legalContactHeading: 'Contact',
    legalDisclaimerHeading: 'Disclaimer',
    legalDisclaimerText: 'This website is provided "as is" without warranty of any kind, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. I do not accept liability for any direct, indirect, incidental, or consequential damages arising from the use of this site, to the extent permitted by law.',
    privacyTitle: 'Privacy Policy',
    privacyIntroHeading: '2. Overview of data processing',
    privacyIntroText: 'This website processes personal data only to the extent necessary for its operation and for the contact form. No data is sold or shared with third parties beyond what is described below.',
    privacyContactHeading: 'Contact form',
    privacyContactText: 'The contact form should only transmit the personal data that is necessary to process your enquiry. Replace the placeholder Formspree endpoint in the HTML with your configured provider and make sure its privacy documentation is reflected here.',
    privacyHostingHeading: 'Hosting and server logs',
    privacyHostingText: 'Your final privacy policy should state which hosting provider is used, which technical data may be processed in server logs and how long that data is retained.',
    privacyRightsHeading: 'Your rights',
    privacyRightsText: 'Your final privacy policy should explain the applicable data protection rights and provide a current contact route for privacy enquiries.',
    acceptanceOfTerms:'Acceptance of terms',
    acceptanceOfTermsText:'By accessing and using this portfolio website ("the Site"), you agree to the following terms. I may update these terms from time to time without prior notice.',
    scopeAndPurposeOfThesite:'Scope and purpose of the site',
    scopeAndPurposeOfThesiteText:'This site was developed as part of my personal portfolio during my training as a Full-Stack Developer. It serves to showcase my work and skills and is not intended for commercial use. I cannot guarantee consistent availability, accuracy, or completeness of the content presented.',
    proprietaryRights:'Proprietary rights',
    proprietaryRightsText:'Unless otherwise stated, the content, design, and structure of this website are my own work and may not be copied, distributed, or modified without my permission.',
    useOfTheSite:'Use of the site',
    useOfTheSiteText:'This site may be used for lawful purposes only. Any use for illegal activities, harassment, or attempts to disrupt or exploit its functionality is strictly prohibited.',
    externalLinks:'External links',
    externalLinksText:'This site contains links to external services (e.g. GitHub, LinkedIn). I am not responsible for the content or privacy practices of these third-party sites.',
    questions:'Questions',
    questionText:'For any questions regarding this Legal Notice, please contact me at the email address above.',
    date_updated:'Last updated: September 2026',
    privacyIntroController:'1. Controller',
    hosting:'3. Hosting',
    hostingText:'This site is hosted by ALL-INKL.COM – Neue Medien Münnich, Hauptstraße 68, 02742 Friedersdorf, Germany. When you visit this site, the hosting provider automatically collects information in server log files, such as your IP address, browser type, referring page, and date/time of access. This data is used solely to ensure secure and reliable operation of the site and is not merged with other data sources.',
    contactForm:'4. Contact form',
    contactFormText:'If you use the contact form, the data you provide (name, email address, message) is stored and used exclusively to process your inquiry. The legal basis is Art. 6(1)(b) GDPR (pre-contractual measures) or Art. 6(1)(f) GDPR (legitimate interest in responding to inquiries). Data from the contact form is deleted once your request has been fully processed, unless statutory retention obligations apply.',
    cookies:'5. Cookies',
    cookiesText:'[Placeholder: this site does not currently set its own cookies; this section will be updated if that changes, e.g. through analytics tools.]',
    thirdPartyServices:'6. Third-party services',
    thirdPartyServicesText:'This site loads the font "Poppins" directly from Google Fonts (fonts.googleapis.com). When the page loads, your browser establishes a connection to Google\'s servers, which may transmit your IP address to Google. Google may process this data in accordance with its own privacy policy. [Placeholder: hosting Google Fonts locally instead, to remove this third-party connection, is planned as a later improvement.]',
    yourRights:'7. Your rights',
    yourRightsText:'Under GDPR, you have the right to:',
    yourRightsList1:'request access to your personal data (Art. 15 GDPR)',
    yourRightsList2:'request correction of inaccurate data (Art. 16 GDPR)',
    yourRightsList3:'request deletion of your data (Art. 17 GDPR)',
    yourRightsList4:'request restriction of processing (Art. 18 GDPR)',
    yourRightsList5:'data portability (Art. 20 GDPR)',
    yourRightsList6:'object to processing (Art. 21 GDPR)',
    yourRightsList7:'withdraw consent at any time, without affecting the lawfulness of processing carried out before the withdrawal',
    rightToComplain:'8. Right to complain',
    rightToComplainText:'You have the right to lodge a complaint with a data protection supervisory authority. The competent authority for Baden-Württemberg is the Baden-Württembergische Datenschutzbeauftragter.',
    sslEncryption:'9. SSL/TLS encryption',
    sslEncryptionText:'This site uses SSL/TLS encryption (Let\'s Encrypt). All data transmitted between your browser and this server is encrypted; you can verify this by the padlock icon and "https://" in your browser\'s address bar.',

  },
  de: {
    title: 'Leon Weigang | Portfolio',
    skipContent: 'Zum Inhalt springen',
    homeAria: 'Leon Weigang Startseite',
    languageSwitcher: 'Sprachauswahl',
    mobileNavigation: 'Mobile Navigation',
    menuOpen: 'Menü öffnen',
    menuClose: 'Menü schließen',
    navAbout: 'Über mich',
    navSkills: 'Skills',
    navPortfolio: 'Portfolio',
    navContact: 'Kontakt',
    heroIAm: 'Ich bin',
    heroRole: 'FRONTEND ENTWICKLER',
    heroCta: 'Lass uns reden!',
    scrollAbout: 'Zu Über mich scrollen',
    scrollDown: 'Nach unten',
    aboutTitle: 'Über mich',
    aboutLead: 'Hey, ich bin Leon!<br>Ich entwickle moderne, benutzerfreundliche Webanwendungen und löse gerne Probleme mit sauberem, strukturiertem Code.',
    aboutLocated: 'Ansässig in Stuttgart — offen für Remote, Hybrid-Modelle oder einen Umzug für die richtige Gelegenheit.',
    aboutMindset: 'Ich bin aufgeschlossen, neugierig und motiviert, neue Technologien zu lernen und meine Fähigkeiten kontinuierlich weiterzuentwickeln.',
    aboutProblem: 'Ich gehe Herausforderungen analytisch und kreativ an, lerne aus jedem Problem und suche durch Ausdauer und Zusammenarbeit nach effizienten Lösungen.',
    skillsTitle: 'Skills',
    skillsText: 'Ich arbeite gerne an unterschiedlichen Projekten mit modernen Frontend-Technologien wie HTML, CSS, JavaScript, TypeScript und Angular. Gleichzeitig bin ich offen dafür, neue Technologien zu lernen und mich weiterzuentwickeln, weil kontinuierliche Weiterbildung in der schnelllebigen Webentwicklung wichtig ist.',
    skillsQuestion: 'Du suchst nach <span>einem weiteren Skill?</span>',
    skillsQuestionText: 'Ich lerne mit Begeisterung neue Technologien und Frameworks.',
    getInTouch: 'Kontakt aufnehmen',
    portfolioTitle: 'Portfolio',
    portfolioText: 'Hier findest du eine Auswahl meiner Arbeiten – Interagiere mit den Projekten<br class="desktop-only"> und entdecke meine Skills in Aktion.',
    openProject: 'Projekt öffnen ↗',
    openElPolloLoco: 'El Pollo Loco Projekt öffnen',
    openJoin: 'JOIN Projekt öffnen',
    openDaBubble: 'daBubble Projekt öffnen',
    openPokedex: 'Pokédex Projekt öffnen',
    testimonialSection: 'Referenzen',
    testimonialControls: 'Referenz-Navigation',
    previousTestimonial: 'Vorherige Referenz',
    nextTestimonial: 'Nächste Referenz',
    testimonialNumber: 'Referenz {number}',
    contactTitle: 'Kontakt',
    contactHeading: 'Du hast ein Problem zu lösen?',
    contactText: 'Erzähl mir, was du suchst und für welche Rolle du dich interessierst. Ich unterstütze deine Projekte gerne mit zuverlässiger und durchdachter Frontend-Entwicklung.',
    contactCta: 'Du suchst einen Frontend-Entwickler? <strong>Kontaktiere mich!</strong>',
    nameLabel: 'Dein Name',
    namePlaceholder: 'Dein Name',
    emailLabel: 'Deine E-Mail',
    emailPlaceholder: 'Deine E-Mail',
    messageLabel: 'Deine Nachricht',
    messagePlaceholder: 'Deine Nachricht',
    privacyConsent: 'Ich habe die <a href="privacy-policy.html">Datenschutzerklärung</a> gelesen und stimme der Verarbeitung meiner Daten wie dort beschrieben zu.',
    sendMessage: 'Nachricht senden :)',
    backToTop: 'Nach oben',
    legalNotice: 'Impressum',
    validationName: 'Bitte gib mindestens 2 Zeichen ein.',
    validationEmail: 'Bitte gib eine gültige E-Mail-Adresse ein.',
    validationMessage: 'Bitte gib mindestens 10 Zeichen ein.',
    validationPrivacy: 'Bitte bestätige die Datenschutzerklärung.',
    endpointMissing: 'Bitte hinterlege zuerst deinen Formular-Endpunkt.',
    sending: 'Wird gesendet ...',
    success: 'Danke! Deine Nachricht wurde erfolgreich gesendet.',
    failure: 'Die Nachricht konnte nicht gesendet werden. Bitte versuche es später erneut.',
    learningPopup: 'Ich habe ein besonderes Interesse am Lernen',
    learningPython: 'Python',
    learningKi: 'Ki',
    github: 'Github',
    liveTest: 'Live test',
    projectElPolloLocoTitle: 'El Pollo Loco',
    projectElPolloLocoDescription: 'Jump-and-run-Spiel auf objektorientierter Basis. Hilf Pepe dabei, Münzen und Tabasco-Salsa zu finden und gegen die verrückte Henne zu kämpfen.',
    projectElPolloLocoTech: 'JavaScript | HTML | CSS',
    projectJoinTitle: 'Join',
    projectJoinDescription: 'Auf dem Kanban-System basierender Task-Manager. Erstelle und organisiere Aufgaben per Drag-and-Drop und weise Benutzer und Kategorien zu.',
    projectJoinTech: 'Angular | TypeScript | HTML | CSS | Firebase',
    projectDaBubbleTitle: 'daBubble',
    projectPokedexTitle: 'Pokédex',
    projectPlaceholderDescription: 'Projektbeschreibung hier ergänzen.',
    projectPlaceholderTech: 'Technologien hier ergänzen.',
    altElPolloLoco: 'Projektvorschau von El Pollo Loco',
    altJoin: 'Projektvorschau von JOIN',
    altDaBubble: 'Projektvorschau von daBubble',
    altPokedex: 'Projektvorschau des Pokédex',
    legalPageTitle: 'Impressum | Leon Weigang',
    privacyPageTitle: 'Datenschutz | Leon Weigang',
    navBack: 'Zurück zum Portfolio',
    legalTitle: 'Impressum',
    legalImprintHeading: 'Angaben gemäß Impressum',
    legalContactHeading: 'Kontakt',
    legalDisclaimerHeading: 'Haftungsausschluss',
    legalDisclaimerText: 'Diese Website wird „wie besehen“ ohne jegliche ausdrückliche oder stillschweigende Gewährleistung bereitgestellt, einschließlich, aber nicht beschränkt auf stillschweigende Gewährleistungen der Marktgängigkeit, Eignung für einen bestimmten Zweck oder Nichtverletzung von Rechten Dritter. Ich übernehme, soweit gesetzlich zulässig, keine Haftung für direkte, indirekte, beiläufig entstandene oder Folgeschäden, die sich aus der Nutzung dieser Website ergeben.',
    privacyTitle: 'Datenschutzerklärung',
    privacyIntroHeading: '2. Übersicht der Datenverarbeitung',
    privacyIntroText: 'Diese Website verarbeitet personenbezogene Daten nur in dem Umfang, der für ihren Betrieb und das Kontaktformular erforderlich ist. Es werden keine Daten verkauft oder über das unten Beschriebene hinaus an Dritte weitergegeben.',
    privacyContactHeading: 'Kontaktformular',
    privacyContactText: 'Das Kontaktformular sollte nur die personenbezogenen Daten übertragen, die zur Bearbeitung deiner Anfrage erforderlich sind. Ersetze den Platzhalter-Endpunkt von Formspree durch deinen konfigurierten Anbieter und berücksichtige dessen Datenschutzinformationen.',
    privacyHostingHeading: 'Hosting und Server-Logs',
    privacyHostingText: 'In deiner endgültigen Datenschutzerklärung sollte stehen, welcher Hostinganbieter eingesetzt wird, welche technischen Daten in Server-Logs verarbeitet werden können und wie lange diese Daten gespeichert werden.',
    privacyRightsHeading: 'Deine Rechte',
    privacyRightsText: 'Die endgültige Datenschutzerklärung sollte die jeweils geltenden Datenschutzrechte erläutern und einen aktuellen Kontaktweg für Datenschutzanfragen nennen.',
    acceptanceOfTerms:'Nutzungsbedingungen',
    acceptanceOfTermsText:'Mit dem Zugriff auf und der Nutzung dieser Portfolio-Website („die Website“) stimmen Sie den folgenden Bedingungen zu. Ich kann diese Bedingungen jederzeit ohne vorherige Ankündigung aktualisieren.',
    scopeAndPurposeOfThesite:'Zweck der Website',
    scopeAndPurposeOfThesiteText:'Diese Website wurde im Rahmen meines persönlichen Portfolios während meiner Ausbildung zum Full-Stack-Entwickler entwickelt. Sie dient der Präsentation meiner Arbeiten und Fähigkeiten und ist nicht für kommerzielle Zwecke bestimmt. Für die durchgehende Verfügbarkeit, Richtigkeit oder Vollständigkeit der dargestellten Inhalte kann ich keine Gewähr übernehmen.',
    proprietaryRights:'Urheberrecht',
    proprietaryRightsText:'Sofern nicht anders angegeben, sind Inhalt, Design und Struktur dieser Website meine eigene Arbeit und dürfen ohne meine Erlaubnis weder kopiert, verbreitet noch verändert werden.',
    useOfTheSite:'Nutzung der Website',
    useOfTheSiteText:'Diese Website darf ausschließlich für rechtmäßige Zwecke genutzt werden. Jegliche Nutzung für illegale Aktivitäten, Belästigung oder Versuche, die Funktionalität zu stören oder auszunutzen, ist strengstens untersagt.',
    externalLinks:'Externe Links',
    externalLinksText:'Diese Website enthält Links zu externen Diensten (z. B. GitHub, LinkedIn). Für die Inhalte oder Datenschutzpraktiken dieser Drittanbieter-Websites übernehme ich keine Verantwortung.',
    questions:'Fragen',
    questionText:'Bei Fragen zu diesem Impressum kontaktieren Sie mich bitte unter der oben genannten E-Mail-Adresse. Stand: Juli 2026',
    date_updated:'Stand: September 2026',
    privacyIntroController:'1. Verantwortlicher',
    hosting:'3. Hosting',
    hostingText:'Diese Website wird gehostet bei ALL-INKL.COM – Neue Medien Münnich, Hauptstraße 68, 02742 Friedersdorf. Beim Besuch dieser Website erfasst der Hosting-Anbieter automatisch Informationen in Server-Logdateien, wie Ihre IP-Adresse, Browsertyp, verweisende Seite und Datum/Uhrzeit des Zugriffs. Diese Daten dienen ausschließlich der Sicherstellung eines sicheren und zuverlässigen Betriebs der Website und werden nicht mit anderen Datenquellen zusammengeführt.',
    contactForm:'4. Kontaktformular',
    contactFormText:'Wenn Sie das Kontaktformular nutzen, werden die von Ihnen angegebenen Daten (Name, E-Mail-Adresse, Nachricht) gespeichert und ausschließlich zur Bearbeitung Ihrer Anfrage verwendet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (vorvertragliche Maßnahmen) bzw. Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an der Beantwortung von Anfragen). Die Daten aus dem Kontaktformular werden gelöscht, sobald Ihre Anfrage vollständig bearbeitet wurde, sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen.',
    cookies:'5. Cookies',
    cookiesText:'[Platzhalter: Diese Website setzt derzeit keine eigenen Cookies; dieser Abschnitt wird aktualisiert, sollte sich das ändern, z. B. durch Analyse-Tools.]',
    thirdPartyServices:'6. Drittanbieter-Dienste',
    thirdPartyServicesText:'Diese Website lädt die Schriftart „Poppins“ direkt von Google Fonts (fonts.googleapis.com). Beim Laden der Seite baut Ihr Browser eine Verbindung zu den Servern von Google auf, wodurch Ihre IP-Adresse an Google übermittelt werden kann. Google verarbeitet diese Daten gegebenenfalls gemäß seiner eigenen Datenschutzerklärung. [Platzhalter: Das lokale Hosting von Google Fonts, um diese Drittanbieter-Verbindung zu entfernen, ist als spätere Verbesserung geplant.]',
    yourRights:'7. Ihre Rechte',
    yourRightsText:'Nach der DSGVO haben Sie das Recht auf:',
    yourRightsList1:'Auskunft über Ihre personenbezogenen Daten (Art. 15 DSGVO)',
    yourRightsList2:'Berichtigung unrichtiger Daten (Art. 16 DSGVO)',
    yourRightsList3:'Löschung Ihrer Daten (Art. 17 DSGVO)',
    yourRightsList4:'Einschränkung der Verarbeitung (Art. 18 DSGVO)',
    yourRightsList5:'Datenübertragbarkeit (Art. 20 DSGVO)',
    yourRightsList6:'Widerspruch gegen die Verarbeitung (Art. 21 DSGVO)',
    yourRightsList7:'jederzeitigen Widerruf Ihrer Einwilligung, ohne dass die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung berührt wird',
    rightToComplain:'8. Beschwerderecht',
    rightToComplainText:'Sie haben das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Zuständige Behörde für Baden-Württemberg ist der Baden-Württembergische Datenschutzbeauftragte.',
    sslEncryption:'9. SSL-/TLS-Verschlüsselung',
    sslEncryptionText:'Diese Website nutzt eine SSL-/TLS-Verschlüsselung (Let\'s Encrypt). Alle zwischen Ihrem Browser und diesem Server übertragenen Daten sind verschlüsselt; erkennbar am Schloss-Symbol und „https://“ in der Adresszeile Ihres Browsers.',
  }
};

const testimonials = [
  {
    en: {
      text: 'Working with Leon was highly constructive. He combines clear communication with a strong attention to detail. He demonstrated exceptional commitment to the project, regularly going the extra mile to resolve critical hurdles. Leon was also responsible for the project\'s most substantial core component, which he mastered with outstanding technical skill and efficiency.',
      author: 'Curtis N.W. - Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/curtis.png'
    },
    de: {
      text: 'Die Zusammenarbeit mit Leon war äußerst konstruktiv. Er verbindet klare Kommunikation mit großer Liebe zum Detail. Er zeigte außergewöhnliches Engagement für das Projekt und scheute keine Mühen, um kritische Hürden zu überwinden. Leon war zudem für die wichtigste Kernkomponente des Projekts verantwortlich, die er mit herausragendem technischem Können und großer Effizienz meisterte.',
      author: 'Curtis N.W. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/curtis.png'
    }
  },
  {
    en: {
      text: 'Leon was a fantastic team member, on whom you can always rely completely. He stands out through a focused approach to work and was significantly responsible for the technical foundation of our project. He implemented this key element with great skill and attention to detail. In our group meetings, Leon shone through clear and understandable communication and was always ready to help the team. His expertise and commitment were a real asset to our project.',
      author: 'Kamil M. – Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/Kamil.png'
    },
    de: {
      text: 'Leon war ein fantastischer Teampartner, auf den man sich jederzeit voll verlassen konnte. Er zeichnete sich durch eine fokussierte Arbeitsweise aus und war maßgeblich für das technische Fundament unseres Projekts verantwortlich. Dieses Schlüsselelement setzte er mit großem Geschick und Liebe zum Detail um. In unseren Gruppengesprächen glänzte Leon durch eine klare, verständliche Kommunikation und stand dem Team immer hilfsbereit zur Seite. Seine Expertise und sein Engagement waren ein echter Gewinn für unser Projekt.',
      author: 'Kamil M. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/Kamil.png'
    }
  },
  {
    en: {
      text: 'Thanks to his exceptional dedication and perseverance, Leon has made a major contribution to the project. Even when faced with difficult problems, he kept at it – often late into the night – and impressed with his meticulous work and high standards.',
      author: 'Annika E. – Team Partner',
      role: 'YOUR PHOTO',
      image: 'assets/testimonial_section/annika.png'
    },
    de: {
      text: 'Leon hat durch seinen außergewöhnlichen Einsatz und seine Ausdauer einen großen Beitrag zum Projekt geleistet. Auch bei schwierigen Problemen blieb er dran – oft bis spät in die Nacht – und überzeugte mit sorgfältiger Arbeit und hoher Qualität.',
      author: 'Annika E. – Teampartner',
      role: 'DEIN FOTO',
      image: 'assets/testimonial_section/annika.png'
    }
  }
];

export { translations, testimonials };
